name: food_ordering_workflow
description: A single-workflow Flutter app demonstrating ordering food with BloC architecture.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
